# Generated by Django 3.0.5 on 2020-08-13 14:01

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_adresa', models.TextField(default=None, max_length=500)),
                ('lozinka', models.TextField(default=None, max_length=500)),
                ('ime', models.TextField(default=None, max_length=500)),
                ('prezime', models.TextField(default=None, max_length=500)),
                ('broja_telefona', models.TextField(default=None, max_length=500)),
                ('jedinstveni_broj_osiguranika', models.TextField(default=None, max_length=500)),
                ('datum', models.DateTimeField(default=None, max_length=500)),
                ('naziv_klinike', models.TextField(default=None, max_length=500)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Klinika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.TextField(default=None, max_length=500)),
                ('adresa', models.TextField(default=None, max_length=500)),
                ('opis', models.TextField(default=None, max_length=500)),
                ('ocena', models.FloatField(default=-1.0)),
                ('cena', models.FloatField(default=500)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lekar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_adresa', models.TextField(default=None, max_length=500)),
                ('lozinka', models.TextField(default=None, max_length=500)),
                ('ime', models.TextField(default=None, max_length=500)),
                ('prezime', models.TextField(max_length=500)),
                ('broja_telefona', models.TextField(default=None, max_length=500)),
                ('jedinstveni_broj_osiguranika', models.TextField(default=None, max_length=500)),
                ('datum', models.DateTimeField(default=None, max_length=500)),
                ('radno_mesto', models.TextField(default=None, max_length=500)),
                ('pozicija', models.TextField(default=None, max_length=500)),
                ('ocena', models.FloatField(default=-1.0)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Odmor',
            fields=[
                ('id', models.CharField(default=None, max_length=500, primary_key=True, serialize=False)),
                ('klinika', models.CharField(default=None, max_length=500)),
                ('lekar', models.CharField(default=None, max_length=500)),
                ('vreme', models.DateTimeField(default=None, max_length=500)),
                ('duzina', models.IntegerField(default=10)),
                ('aktiviran', models.IntegerField(default=0)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.TextField(default=None, max_length=500)),
                ('naziv', models.TextField(default=None, max_length=500)),
                ('id_klinike_kojoj_pripada', models.TextField(default=None, max_length=500)),
                ('opis', models.TextField(default=None, max_length=500)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
