# Generated by Django 2.2.12 on 2020-04-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model Podataka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacijent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_adresa', models.CharField(max_length=500)),
                ('lozinka', models.CharField(max_length=500)),
                ('ime', models.CharField(max_length=500)),
                ('prezime', models.CharField(max_length=500)),
                ('adresa_prebivalista', models.CharField(max_length=500)),
                ('grad', models.CharField(max_length=500)),
                ('drzava', models.CharField(max_length=500)),
                ('broja_telefona', models.CharField(max_length=500)),
                ('jedinstveni_broj_osiguranika', models.CharField(max_length=500)),
            ],
        ),
    ]
