# Generated by Django 2.2.12 on 2020-04-14 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0002_pacijent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacijent',
            name='alergije_na_lek',
            field=models.CharField(default='Prazno', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacijent',
            name='datum',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacijent',
            name='diagnoza',
            field=models.CharField(default='Prazno', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacijent',
            name='dioptrija',
            field=models.CharField(default='Prazno', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacijent',
            name='krvna_grupa',
            field=models.CharField(default='Prazno', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacijent',
            name='lekovi',
            field=models.CharField(default='Prazno', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacijent',
            name='sifra_bolesti',
            field=models.CharField(default='Prazno', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacijent',
            name='tezina',
            field=models.CharField(default='Prazno', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacijent',
            name='visina',
            field=models.CharField(default='Prazno', max_length=500),
            preserve_default=False,
        ),
    ]
