# Generated by Django 3.0.5 on 2020-04-17 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0003_auto_20200414_1347'),
        ('Model_Podataka', '0003_lekar'),
    ]

    operations = [
    ]
