# Generated by Django 3.0.5 on 2020-04-21 11:34

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0007_auto_20200421_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_adresa', models.TextField(max_length=500)),
                ('lozinka', models.TextField(max_length=500)),
                ('ime', models.TextField(max_length=500)),
                ('prezime', models.TextField(max_length=500)),
                ('broja_telefona', models.TextField(max_length=500)),
                ('jedinstveni_broj_osiguranika', models.TextField(max_length=500)),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('naziv_klinike', models.TextField(max_length=500)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
