# Generated by Django 3.0.5 on 2020-04-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0008_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='klinika',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='lekar',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='sala',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='broja_telefona',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='admin',
            name='datum',
            field=models.DateTimeField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='admin',
            name='email_adresa',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='admin',
            name='ime',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='admin',
            name='jedinstveni_broj_osiguranika',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='admin',
            name='lozinka',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='admin',
            name='naziv_klinike',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='admin',
            name='prezime',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='klinika',
            name='adresa',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='klinika',
            name='naziv',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='klinika',
            name='opis',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='broja_telefona',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='datum',
            field=models.DateTimeField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='email_adresa',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='ime',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='jedinstveni_broj_osiguranika',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='lozinka',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='pozicija',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='radno_mesto',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='adresa_prebivalista',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='broja_telefona',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='drzava',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='email_adresa',
            field=models.CharField(default=None, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='grad',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='ime',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='jedinstveni_broj_osiguranika',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='lozinka',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='prezime',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='sala',
            name='broj',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='sala',
            name='id_klinike_kojoj_pripada',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='sala',
            name='naziv',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='sala',
            name='opis',
            field=models.TextField(default=None, max_length=500),
        ),
    ]
