# Generated by Django 3.0.5 on 2020-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0009_auto_20200427_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacijent',
            name='datum',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='tezina',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='pacijent',
            name='visina',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
