# Generated by Django 3.0.5 on 2020-05-01 08:15

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0011_auto_20200427_2105'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='klinika',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lekar',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sala',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
