# Generated by Django 3.0.5 on 2020-05-09 10:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0012_auto_20200501_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregled',
            fields=[
                ('id', models.CharField(default=None, max_length=500, primary_key=True, serialize=False)),
                ('klinika', models.CharField(default=None, max_length=500)),
                ('zakazan', models.CharField(default=None, max_length=500)),
                ('lekar', models.CharField(default=None, max_length=500)),
                ('sala', models.CharField(default=None, max_length=500)),
                ('tip_pregleda', models.CharField(default=None, max_length=500)),
                ('vreme', models.DateTimeField(default=None, max_length=500)),
                ('sifra_bolesti', models.CharField(default=None, max_length=500)),
                ('diagnoza', models.CharField(default=None, max_length=500)),
                ('lekovi', models.CharField(default=None, max_length=500)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
