# Generated by Django 3.0.5 on 2020-05-12 11:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0012_auto_20200501_1015'),
    ]


