# Generated by Django 3.0.5 on 2020-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0013_auto_20200502_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacijent',
            name='datum',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
