# Generated by Django 3.0.5 on 2020-05-15 14:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0013_auto_20200512_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odmor',
            fields=[
                ('id', models.CharField(default=None, max_length=500, primary_key=True, serialize=False)),
                ('klinika', models.CharField(default=None, max_length=500)),
                ('lekar', models.CharField(default=None, max_length=500)),
                ('vreme', models.DateTimeField(default=None, max_length=500)),
                ('duzina', models.IntegerField(default=10)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        
    ]
