# Generated by Django 3.0.5 on 2020-05-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0015_pregled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregled',
            name='karton_pacijenta',
        ),
    ]
