# Generated by Django 3.0.5 on 2020-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0016_remove_pregled_karton_pacijenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregled',
            name='id',
            field=models.CharField(default=None, max_length=500, primary_key=True, serialize=False),
        ),
    ]
