# Generated by Django 3.0.5 on 2020-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0015_auto_20200515_1425'),
    ]

    
