# Generated by Django 3.0.5 on 2020-06-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0017_auto_20200516_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pacijent',
        ),
        migrations.AddField(
            model_name='klinika',
            name='ocena',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='lekar',
            name='ocena',
            field=models.FloatField(default=-1),
        ),
    ]
