# Generated by Django 3.0.5 on 2020-05-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0019_remove_pregled_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacijent',
            name='aktiviran',
            field=models.IntegerField(default=1, max_length=500),
        ),
    ]
