# Generated by Django 3.0.5 on 2020-05-13 16:07

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0021_auto_20200511_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacije',
            fields=[
                ('id', models.CharField(default=None, max_length=500, primary_key=True, serialize=False)),
                ('klinika', models.CharField(default=None, max_length=500)),
                ('pacijent', models.CharField(default=None, max_length=500)),
                ('lekari', models.CharField(default=None, max_length=500)),
                ('sala', models.CharField(default=None, max_length=500)),
                ('tip_operacije', models.CharField(default=None, max_length=500)),
                ('vreme', models.DateTimeField(default=None, max_length=500)),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
