# Generated by Django 3.0.5 on 2020-05-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0023_merge_20200516_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacije',
            name='klinika',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='operacije',
            name='lekari',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='operacije',
            name='pacijent',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='operacije',
            name='sala',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='operacije',
            name='tip_operacije',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='operacije',
            name='vreme',
            field=models.DateTimeField(default=None, max_length=500),
        ),
    ]
