# Generated by Django 3.0.5 on 2020-05-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0017_auto_20200516_1648'),
        ('Model_Podataka', '0025_pregled_prihvacen'),
    ]

    operations = [
    ]
