# Generated by Django 3.0.5 on 2020-05-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0026_merge_20200517_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operacije',
        ),
        migrations.DeleteModel(
            name='Pacijent',
        ),
        migrations.DeleteModel(
            name='Pregled',
        ),
    ]
