# Generated by Django 3.0.5 on 2020-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0028_auto_20200524_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klinika',
            name='ocena',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='lekar',
            name='ocena',
            field=models.FloatField(default=-1),
        ),
    ]
