# Generated by Django 3.0.5 on 2020-06-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model_Podataka', '0029_auto_20200524_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='klinika',
            name='cena',
            field=models.FloatField(default=500),
        ),
    ]
