from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index', views.index, name='index'),
    path('', views.index),
    path('superadmin/register', views.register_clinic_admin),
    path('login', views.login_pacijent),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
    path('pacijent/registracijaPacijent', views.registracijaPacijent,  name='registracijaPacijent'),
    path('pacijent/glavnaStranicaPacijent', views.glavnaStranicaPacijent, name = 'glavnaStranicaPacijent'),
    path('pacijent/licniPodaciPacijent', views.licniPodaciPacijent, name = 'licniPodaciPacijent'),
    path('pacijent/promenaLicniPodaciPacijent', views.promenaLicniPodaciPacijent, name = 'promenaLicniPodaciPacijent'),
    path('pacijent/zdravstveniKartonPacijent', views.zdravstveniKartonPacijent, name = 'zdravstveniKartonPacijent'),
    path('pacijent/prikazKlinikaPacijent', views.prikazKlinikaPacijent, name = 'prikazKlinikaPacijent'),
    path('pacijent/prikazLekaraKlinikePacijent', views.prikazLekaraKlinikePacijent, name = 'prikazLekaraKlinikePacijent'),
    path('pacijent/prikazKlinikaPacijentSortirano', views.prikazKlinikaPacijentSortirano, name = 'prikazKlinikaPacijentSortirano'),
    path('pacijent/pretragaKlinikaPacijent', views.pretragaKlinikaPacijent, name = 'pretragaKlinikaPacijent'),
    path('pacijent/sortiranjeLekaraPacijent', views.sortiranjeLekaraPacijent, name = 'sortiranjeLekaraPacijent'),
    path('pacijent/pretragaLekaraPacijent', views.pretragaLekaraPacijent, name = 'pretragaLekaraPacijent'),
    path('pacijent/prikaziBrzePreglede', views.prikaziBrzePreglede, name = 'prikaziBrzePreglede'),
    path('pacijent/zakaziBrzPregled', views.zakaziBrzPregled, name = 'zakaziBrzPregled'),
    path('pacijent/sviPreglediPacijent', views.sviPreglediPacijent, name = 'sviPreglediPacijent'),
    path('pacijent/otkaziPregledPacijent', views.otkaziPregledPacijent, name = 'otkaziPregledPacijent'),
    path('lekar/izmeni', views.izmeni_lekara),
    path('sala/izmeni', views.izmeni_salu),
    path('klinika/izmeni', views.izmeni_kliniku),
    path('registerLekara', views.registerLekara, name='registerLekara'),
    path('registerLekar', views.registerLekara, name='registerLekar'),# vraca error ako obrisem
    path('registerAdmina', views.registerAdmina, name='registerAdmina'),
    path('promeniLozinku', views.promeniLozinku, name='promeniLozinku'),
    path('IzlogujSe', views.IzlogujSe, name='IzlogujSe'),
    path('Omeni', views.Omeni, name='Omeni'),
    path('IzmeniKorisnika', views.IzmeniKorisnika, name='IzmeniKorisnika'),
    path('pogledajPacijente', views.pogledajPacijente, name='pogledajPacijente'),
    path('PogledajPacijenta', views.PogledajPacijenta, name='PogledajPacijenta'),
    path('pogledajSale', views.pogledajSale, name='pogledajSale'),
    path('pogledajSalu', views.pogledajSalu, name='pogledajSalu'),
    path('IzmeniSalu', views.IzmeniSalu, name='IzmeniSalu'),
    path('ObrisiSalu', views.ObrisiSalu, name='ObrisiSalu'),
    path('DodajSalu', views.DodajSalu, name='DodajSalu'),
    path('pogledajKlinike', views.pogledajKlinike, name='pogledajKlinike'),
    path('pogledajKliniku', views.pogledajKliniku, name='pogledajKliniku'),
    path('IzmeniKliniku', views.IzmeniKliniku, name='IzmeniKliniku'),
    path('pogledajLekare', views.pogledajLekare, name='pogledajLekare'),
    path('PogledajLekara', views.PogledajLekara, name='PogledajLekara'),
    path('IzmeniLekara', views.IzmeniLekara, name='IzmeniLekara'),
    path('ObrisiLekara', views.ObrisiLekara, name='ObrisiLekara'),
    path('PogledajTermine', views.PogledajTermine, name='PogledajTermine'),
    path('PogledajTermin', views.PogledajTermin, name='PogledajTermin'),
    path('ObrisiTermin', views.ObrisiTermin, name='ObrisiTermin'),
    path('IzmeniTermin', views.IzmeniTermin, name='IzmeniTermin'),
    path('DodajTermin', views.DodajTermin, name='DodajTermin'),
    path('DodajOdmor', views.DodajOdmor, name='DodajOdmor'),
    path('OdobriOdmor', views.OdobriOdmor, name='OdobriOdmor'),
    path('PogledajStanje', views.PogledajStanje, name='PogledajStanje'),
]
