# Generated by Django 3.0.5 on 2020-05-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacijent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregled',
            name='ocenaKlinike',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pregled',
            name='ocenaLekara',
            field=models.IntegerField(default=-1),
        ),
    ]
