# Generated by Django 3.0.5 on 2020-08-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacijent', '0002_tippregleda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tippregleda',
            name='cena',
            field=models.FloatField(default=1500, max_length=500),
        ),
        migrations.AlterField(
            model_name='tippregleda',
            name='trajanje',
            field=models.FloatField(default=15, max_length=500),
        ),
    ]
