# Generated by Django 3.0.5 on 2020-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacijent', '0002_auto_20200524_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregled',
            name='ocenaKlinike',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='pregled',
            name='ocenaLekara',
            field=models.FloatField(default=-1),
        ),
    ]
